apiVersion: apps/v1
kind: Deployment
metadata:
  name: notestaker-deployment
  labels:
    app: notestaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notestaker
  template:
    metadata:
      labels:
        app: notestaker
    spec:
      containers:
      - name: notestaker
        image: rameshkumarverma/notestaker:latest
        ports:
        - containerPort: 3000
        - containerPort: 8000
        # Add liveness and readiness probes
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3 # Increase the failure threshold
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3 # Increase the failure threshold
